time_zone: America/Bogota

default_config:

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# ===============================
# Sensores de reloj actualizados cada segundo (AM/PM + Fecha larga)
# ===============================
template:
  - trigger:
      - platform: time_pattern
        seconds: "/1"
    sensor:
      - name: "Hora AM/PM"
        unique_id: hora_am_pm
        state: "{{ now().strftime('%I:%M:%S %p') }}"
        icon: mdi:clock

      - name: "Fecha Larga"
        unique_id: fecha_larga
        state: >-
          {% set dias = ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"] %}
          {% set meses = ["enero", "febrero", "marzo", "abril", "mayo", "junio",
                          "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"] %}
          {{ dias[now().weekday()] }}, {{ now().day }} de {{ meses[now().month -1] }} de {{ now().year }}
        icon: mdi:calendar

# ===============================
# Entidades de tiempo (horarios)
# ===============================
input_datetime:
  timbre_1:
    name: "Timbre 1"
    has_date: false
    has_time: true
  timbre_2:
    name: "Timbre 2"
    has_date: false
    has_time: true
  timbre_3:
    name: "Timbre 3"
    has_date: false
    has_time: true
  timbre_4:
    name: "Timbre 4"
    has_date: false
    has_time: true
  timbre_5:
    name: "Timbre 5"
    has_date: false
    has_time: true
  timbre_6:
    name: "Timbre 6"
    has_date: false
    has_time: true
  timbre_7:
    name: "Timbre 7"
    has_date: false
    has_time: true
  timbre_8:
    name: "Timbre 8"
    has_date: false
    has_time: true
  hora_apagado_auto:
    name: "Hora apagado automático"
    has_date: false
    has_time: true

# ===============================
# Botones booleanos (encendido/apagado)
# ===============================
input_boolean:
  timbre_9_button:
    name: "Timbre 9 - Botón"
    initial: off
  timbre_10_button:
    name: "Timbre 10 - Botón"
    initial: off
  activar_apagado_automatico:
    name: "Activar apagado automático"
  guardar_configuracion:
    name: "Guardar Configuración"
    initial: off
  eliminar_configuracion:
    name: "Eliminar Configuración"
    initial: off

# ===============================
# Entradas numéricas (repeticiones y delays)
# ===============================
input_number:
  numero_de_timbres:
    name: "Repeticiones Timbre (Global)"
    initial: 1
    min: 1
    max: 4
    step: 1
  numero_de_timbres_timbre9:
    name: "Repeticiones Timbre 9"
    initial: 2
    min: 1
    max: 4
    step: 1
  numero_de_timbres_timbre10:
    name: "Repeticiones Timbre 10"
    initial: 10
    min: 1
    max: 10
    step: 1
  numero_ejecuciones_timbre10:
    name: "Ejecuciones Timbre 10"
    initial: 10
    min: 1
    max: 10
    step: 1
  delay_entre_ejecuciones_timbre10:
    name: "Delay entre ejecuciones (s)"
    initial: 1
    min: 1
    max: 10
    step: 1

# ===============================
# Sensores (JSON generado por Python + Hora/Fecha del sistema)
# ===============================
sensor:
  - platform: command_line
    name: horarios_timbres
    command: "cat /homeassistant/horarios_timbres_output.json"
    scan_interval: 300

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'time_date'

# ===============================
# Contadores (para LED u otros efectos)
# ===============================
counter:
  led_changes:
    initial: 0
    step: 1

# ===============================
# Entradas de texto (gestión de configuraciones)
# ===============================
input_text:
  horario_nombre:
    name: "Nombre del Horario"
    initial: ""
    max: 50
  horario_descripcion:
    name: "Descripción del Horario"
    initial: ""
    max: 100
  horario_cargado_nombre:
    name: "Nombre del horario cargado"
    initial: ""
    max: 50
  horario_cargado_descripcion:
    name: "Descripción del horario cargado"
    initial: ""
    max: 100
  horarios_guardados_serializados:
    name: "Horarios guardados serializados"
    initial: "[]"
    max: 1000
  configuracion_nombre:
    name: "Nombre de la Configuración"
    initial: ""
    max: 50
  configuracion_id_eliminar:
    name: "ID a eliminar"
    initial: ""
    max: 10

# ===============================
# Selectores (para seleccionar horarios guardados)
# ===============================
input_select:
  horarios_guardados:
    name: "Horarios Guardados"
    options:
      - "Selecciona un horario guardado"
    initial: "Selecciona un horario guardado"

# ===============================
# Comandos Shell (operaciones con SQLite)
# ===============================
shell_command:
  guardar_timbres: python3 /config/scripts_py/guardar_timbres.py "{{ timbres_json_escaped }}"
  cargar_timbres: 'python3 /config/cargar_timbres.py'
  eliminar_timbres: 'python3 /config/eliminar_timbres.py "{{ eliminar_timbres_json }}"'
  debug_guardar_timbres: 'python3 /config/scripts_py/guardar_timbres.py "{{ timbres_json_escaped }}" > /config/debug_entrada.txt 2>&1'
